
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - webapp.adershrp.org
  resources:
  - guestbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.adershrp.org
  resources:
  - guestbooks/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.adershrp.org
  resources:
  - guestbooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.adershrp.org
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.adershrp.org
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.adershrp.org
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
